
### Read all users
Get http://localhost:3000/user-api/users
###

### Read a user by id
Get http://localhost:3000/user-api/users/11
###

### Update a existing user
PUT http://localhost:3000/user-api/users
Content-Type:application/json

{
    "id":10,
    "name":"abhi",
    "age":19
}


###

### Create a new user
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id":11,
    "name":"ram",
    "age":20
}



### Delete a user by id

DELETE http://localhost:3000/user-api/users/10

###

//Requests for Products

###Get all products
GET http://localhost:3000/product-api/products
###

###Get product by brand
GET http://localhost:3000/product-api/products/puma
###

###Creae a new product
POST  http://localhost:3000/product-api/products
Content-Type: application/json

{
    "id":1,
    "name":"shoes",
    "brand":"nike",
    "price":20000
}
###

### Modify a existing product
PUT   http://localhost:3000/product-api/products
Content-Type: application/json

{
    "id":1,
    "name":"shoes",
    "brand":"puma",
    "price":12000
}
###

### Delete by a product id
DELETE  http://localhost:3000/product-api/products/1
###